import {
  type AnyCard,
  type GuandanDecisionPoint,
  type LLMReasoningTrace,
  RANK_ORDER,
  isJoker,
} from '@guandan/shared'

export type BaselineTraceAgentId = 'heuristic-legal-first' | 'strategic-heuristic'

export function createBaselineTrace(
  decision: GuandanDecisionPoint,
  agentId: BaselineTraceAgentId,
): LLMReasoningTrace {
  const selectedAction = agentId === 'strategic-heuristic'
    ? chooseStrategicAction(decision)
    : decision.legalActions[0]
  const publicEvidence = decision.publicHistory.slice(0, 3).map(event => event.eventId)
  const objective = chooseObjective(decision, selectedAction.action)

  return {
    schemaVersion: '0.1.0',
    decisionId: decision.decisionId,
    agentId,
    selectedActionId: selectedAction.actionId,
    teamObjective: {
      type: objective,
      explanation: objectiveExplanation(agentId, objective),
    },
    partnerBelief: {
      summary: partnerBeliefSummary(decision),
      confidence: 0.45,
      evidence: publicEvidence,
    },
    opponentBelief: {
      summary: opponentBeliefSummary(decision),
      confidence: 0.45,
      evidence: publicEvidence,
    },
    actionRationale: {
      primaryReason: primaryReason(agentId, selectedAction.action),
      whyNotAlternatives: decision.legalActions
        .filter(action => action.actionId !== selectedAction.actionId)
        .slice(0, 3)
        .map(action => ({
          actionId: action.actionId,
          reason: alternativeReason(agentId),
        })),
    },
    riskAssessment: {
      risks: [riskSummary(agentId)],
      mitigation: mitigationSummary(agentId),
    },
    confidence: agentId === 'strategic-heuristic' ? 0.62 : 0.5,
    notes: agentId === 'strategic-heuristic'
      ? 'Generated by strategic-heuristic for non-LLM baseline comparison.'
      : 'Generated by heuristic-legal-first for verifier pipeline validation.',
  }
}

function chooseStrategicAction(decision: GuandanDecisionPoint): GuandanDecisionPoint['legalActions'][number] {
  const legalPlays = decision.legalActions
    .filter(action => action.action === 'play')
    .sort((a, b) => actionStrength(a.cards) - actionStrength(b.cards))

  if (decision.handCounts[decision.currentPlayer] <= 2 && legalPlays.length > 0) {
    return legalPlays[0]
  }

  if (decision.tableLead && legalPlays.length > 0) {
    return legalPlays[0]
  }

  if (!decision.tableLead && legalPlays.length > 0) {
    return legalPlays[0]
  }

  return decision.legalActions[0]
}

function actionStrength(cards: AnyCard[]): number {
  return cards.reduce((sum, card) => sum + cardStrength(card), 0)
}

function cardStrength(card: AnyCard): number {
  if (isJoker(card)) return card.type === 'big' ? 17 : 16
  return RANK_ORDER[card.rank] + (card.isTrump ? 0.5 : 0)
}

function chooseObjective(
  decision: GuandanDecisionPoint,
  action: 'play' | 'pass',
): LLMReasoningTrace['teamObjective']['type'] {
  if (decision.handCounts[decision.currentPlayer] <= 2 && action === 'play') return 'finish_hand'
  if (decision.tableLead && action === 'play') return 'gain_lead'
  if (decision.scenarioTags.includes('partner_near_finish')) return 'protect_partner'
  if (decision.scenarioTags.includes('opponent_near_finish')) return 'suppress_opponent'
  if (!decision.tableLead && action === 'play') return 'keep_lead'
  return 'save_resources'
}

function objectiveExplanation(
  agentId: BaselineTraceAgentId,
  objective: LLMReasoningTrace['teamObjective']['type'],
): string {
  if (agentId === 'heuristic-legal-first') {
    return 'Use the first legal action only to validate the verifier pipeline.'
  }
  return `Use a deterministic strategic heuristic with objective ${objective}.`
}

function partnerBeliefSummary(decision: GuandanDecisionPoint): string {
  if (decision.scenarioTags.includes('partner_near_finish')) {
    return 'Partner may be close to finishing based on public hand count; hidden cards remain uncertain.'
  }
  return 'Partner state is uncertain; rely only on public hand counts and public events.'
}

function opponentBeliefSummary(decision: GuandanDecisionPoint): string {
  if (decision.scenarioTags.includes('opponent_near_finish')) {
    return 'An opponent may be close to finishing based on public hand count; hidden cards remain uncertain.'
  }
  return 'Opponent state is uncertain; no hidden cards are asserted as facts.'
}

function primaryReason(agentId: BaselineTraceAgentId, action: 'play' | 'pass'): string {
  if (agentId === 'heuristic-legal-first') {
    return action === 'play'
      ? 'Selected a legal play action exposed by the candidate set.'
      : 'Selected a legal pass action exposed by the candidate set.'
  }
  return action === 'play'
    ? 'Selected the lowest legal play action aligned with the current strategic tag.'
    : 'No legal play was available, so selected pass.'
}

function alternativeReason(agentId: BaselineTraceAgentId): string {
  return agentId === 'strategic-heuristic'
    ? 'Alternative was legal but lower priority under the deterministic strategic rule.'
    : 'Alternative kept as a legal candidate for later policy comparison.'
}

function riskSummary(agentId: BaselineTraceAgentId): string {
  return agentId === 'strategic-heuristic'
    ? 'The heuristic is deterministic and local; it does not perform rollout-based team value estimation.'
    : 'The heuristic does not optimize team value; it only validates verifier plumbing.'
}

function mitigationSummary(agentId: BaselineTraceAgentId): string {
  return agentId === 'strategic-heuristic'
    ? 'Report this as a transparent non-LLM strategic baseline with known limitations.'
    : 'Report this as a non-LLM, non-strategic baseline artifact.'
}
